name: krew-release
description: Bump version of your kubectl plugin in krew-index repo
author: Kazuki Suda <kazuki.suda@gmail.com>
runs:
  using: composite
  steps:
  - run: $GITHUB_ACTION_PATH/krew-release.sh
    shell: bash

