name: CI

on:
  push:
    branches: [master]
    paths_ignore: ["**.md"]
  pull_request:
    types: [opened, synchronize]
    paths_ignore: ["**.md"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make lint
