name: setup-krew

on:
  push:
    branches: [master]
    paths: ["setup-krew/**"]
    paths_ignore: ["**.md"]
  pull_request:
    types: [opened, synchronize]
    paths: ["setup-krew/**"]
    paths_ignore: ["**.md"]

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: ./setup-krew
  - run: kubectl krew version
